language: java
jdk:
  - oraclejdk8

script: "mvn clean cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)

install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
before_install:
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --batch --yes; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust --batch --yes; fi
deploy:
-
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    repo: ganchix/morphia-spring-boot-starter
    branch: master
    jdk: oraclejdk8
-
  provider: script
  script: .travis/deploy.sh
  skip_cleanup: true
  on:
    repo: ganchix/morphia-spring-boot-starter
    tags: true
    jdk: oraclejdk8

